### ISSUE TITLE
Custom babel config

### ISSUE THREAD

**Issue by talentlessguy** [osdevisnot/klap#20]
I'd like to make my bundle smaller by passing `loose: true` to `@babel/preset-env` but it seems like there's no way to do this.

I think it would be cool to support babel config out of the box

**Comment by osdevisnot** [comment]
Not sure if I am following, we already pass `loose: true` to `@babel/preset-env` [here](https://github.com/osdevisnot/klap/blob/master/src/babel.js#L24).

**Comment by talentlessguy** [comment]
@osdevisnot well yes but will Klap heavily rely on Babel macros (correct me if I'm wrong) or be able to consume custom config?

for example if I want [`@babel/preset-modules`](https://github.com/babel/preset-modules)

**Comment by osdevisnot** [comment]
As far as customization goes, I don't see value in allowing babel customizations. Installing a babel plugin almost always needs you to install babel core and other dependencies which goes against the `zero dependency` goal for `klap`.

That said, `@babel/preset-modules` is something we should probably do by default. As far as I understand, the benefits of `@babel/preset-modules` are limited to `async/await` and `template literals` language syntaxes. 

And, given that `@babel/preset-modules` is intended to be merged into `@babel/preset-env`, I am inclined towards waiting for that.

**Comment by osdevisnot** [comment]
It seems `@babel/preset-modules` will soon be moved to `@babel/preset-env` - https://github.com/babel/preset-modules/issues/9
