### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by tfrijsewijk** [osdevisnot/klap#231]
Hi,

Great lib! Looks promising. I'm developing a Leaflet plugin and I need to import some library from node_modules for that.

I receive the following error:

```
SyntaxError: Unexpected token (1434:11) in xxx\core\dist\esm\index-65dcb9fa.js
```

Line 1434:

```
    return import(
```

It looks like klap has issues with the lazy `import` statement when an a node_module has `import()`, if I rename it to something else all is fine (but I'm getting runtime errors, obviously).

The imported code is ESM, do you have any idea why `klap` can't handle this?

Thanks!

**Comment by tfrijsewijk** [comment]
So after extensive debugging I narrowed it down to a commented word (`process`) 🤯 

I even made a demo repo: https://github.com/tfrijsewijk/klap-test

In the original source code the comment was:

```
// connectedCallback will be processed once all components have been registered
```

The problem is the word `process`. If you rename it to `Process`, strip of the `s`, whatever -> it works! The comment is from a library I use, which in turn is generated code (Stencil), so I removed it using `patch-package` because I don't have control over it.

But holy smokes! This is weird

**Comment by tfrijsewijk** [comment]
So I want ahead and cloned `klap` and built it locally. After some binary commenting in `./plugins.js` I found out that removing `nodeGlobals(),` fixes the error...

So there's another clue

**Comment by osdevisnot** [comment]
👋 @tfrijsewijk - my apologies for getting back little late on this one, and thank you so much for clear and minimal re-production of the original issue. 

You are also right in narrowing this down to [rollup-plugin-node-globals](https://github.com/calvinmetcalf/rollup-plugin-node-globals). I tried this with simplified rollup build [here](https://gist.github.com/osdevisnot/8de539148d17e04ed86a8252b4140756) and was able to re-produce the issue. This however works ok if you remove the dynamic import from `loader.js`

At this point, I am unsure why this might be the case. We should create an issue with node-globals repo for now to get some feedback.

**Comment by tfrijsewijk** [comment]
Hi @osdevisnot - Don't mention it and thanks for resolving it. I'm upgrading right away :-)
