### ISSUE TITLE
klap adds LICENSE even if LICENSE.md exists

### ISSUE THREAD

**Issue by dnl-brnr** [osdevisnot/klap#29]
Perhaps klap should check to see if a `LICENSE.md` or a `LICENSE.txt` exist before adding `LICENSE`?

**Comment by osdevisnot** [comment]
Good point, we check if the file with same name exists here https://github.com/osdevisnot/klap/blob/master/src/init.js#L86

How would you handle variations?

**Comment by dnl-brnr** [comment]
@osdevisnot Nice! I was working on a similar solution [here](https://github.com/dnl-brnr-forks/klap/blob/26a9978171b82b1e8496afc7ac14f5341d9bc749/src/init.js#L69-L125), the one thing I had left to do was set up `Promise.all`.

**Comment by dnl-brnr** [comment]
@osdevisnot  

Also, I was thinking that the approach I took was transitional and that with more refactoring `defaults` and `templates` could be moved to `create-init.js`. This would probably require them to be converted to functions, so that `pkg` and `template` could be passed as arguments. But a functional approach, I think, would ultimately yield the most extensible solution, allowing for more customizable initialization down the road.

**Comment by osdevisnot** [comment]
Oh my apologies, didn't realize you were working on this. 

Also, I agree the create-init could be more functions based emitting content based on PKG and template. Do you want to PR this out?

**Comment by dnl-brnr** [comment]
No problem at all, I guess I should have signaled somehow it was in progress. Still learning how to open source 🙂. It's really up to you, I'm happy to keep refactoring it, I just don't want to stifle any progress, having you wait out of fear of incompatible APIs, where you might otherwise overhaul things.

**Comment by osdevisnot** [comment]
Honestly, I am not planning to overhaul things other than adding support for `google-closure-compiler`. Feel free to refactor things if it makes the tool better and easier to maintain.
