### ISSUE TITLE
Bundle async function expression used as an IIFE

### ISSUE THREAD

**Issue by marcuslindblom** [osdevisnot/klap#41]
I have this async function expression in my `index.js`

```js
(async () => {

  const store = await createStore({ actions, mutations, initalState });

  store.subscribe(() => {
    console.log(store.state.message);
  });

})();
```

Klap throws an error like this: `Error: 'return' outside of function`.

This is my config:

```json
{
  "name": "minimal",
  "version": "0.0.0",
  "private": true,
  "module": "dist/index.esm.js",
  "source": "src/web/wwwroot/js/index.js",
  "scripts": {
    "build": "klap build"
  },
  "devDependencies": {
    "klap": "^4.2.3"
  }
}
```

Is it possible to fix?

**Comment by marcuslindblom** [comment]
A simple workaround would be to put the above code in a module, import it into index.js and run it. I guess the bundled does not think of the above code as something that would be in an easy module?

**Comment by osdevisnot** [comment]
@marcuslindblom we might have issues with top level await. FWIW, top level awaits seem to be little messy at this time - See https://gist.github.com/Rich-Harris/0b6f317657f5167663b493c722647221

Are you ok using it in a module and importing in `index.js`?

**Comment by marcuslindblom** [comment]
@osdevisnot Yes, I guess that is somewhat the correct way to do it.

Thanks!
