### ISSUE TITLE
Bundle and minify es6 modules breaks the named exports

### ISSUE THREAD

**Issue by marcuslindblom** [osdevisnot/klap#42]
I try to use klap to bundle and minify some vanilla js es modules but it breaks named export/imports. So when I try to use a named export that has been processed by Klap I get an error that the bundle does not have a named export with that particular name.

**Comment by osdevisnot** [comment]
hi @marcuslindblom, thank you for the bug report. Are you able to produce a smallish example to showcase the issue? I've commonly observed this issue when using a `cjs` version in `esm` environment or `esm` version in `cjs` environment. But your case might be different.

**Comment by marcuslindblom** [comment]
@osdevisnot It actually seems to work with a minimal example so I think I need to investigate a bit more. One question though. I use unpgk but when I try to import my Klap bundled script using `https://unpkg.com/browse/@marcuslindblom/klap@0.1.0/` it seems like the script is looking for the `index.js` but my bundled file is located in `dist/index.esm.js`. Is it possible to configure the default file using `project.json`? This is my project file.

```json
{
  "name": "@marcuslindblom/klap",
  "version": "0.0.1-preview.20",
  "files": [
    "dist"
  ],
  "source": "index.js",
  "module": "dist/index.esm.js"
}
```

**Comment by marcuslindblom** [comment]
It seems like maybe `?module` is the right thing to do when using unpkg? It's har du find best practices on using plain js and es modules today so therefore I ask you as a creator of this bundler. I hope that is ok.

**Comment by osdevisnot** [comment]
Hey @marcuslindblom, it's totally ok to ask out. I'm happy to support when I can.

For the usage from `unpkg` you have 2 options:
- append `?module` to url as you said
- add a property called `unpkg` pointing to your `esm` bundle like this - https://github.com/osdevisnot/vertu/blob/master/packages/vertu/package.json#L13

Let me know if any of that helps

**Comment by marcuslindblom** [comment]
@osdevisnot Thanks, the property `unpkg` was exactly what I was looking for.

I have read about bundling and http2 with `modulepreload`. What is your standpoint when it comes to bundling vs using http2 with server push or `modulepreload`? Do I gain anything in performance with one or the other?

**Comment by osdevisnot** [comment]
The performance aspect is almost always specific to the application use case. However I would combine both http2 and bundling to achieve optimal performance.

I am going to close this issue, but feel free to ask out as needed.
